from __future__ import annotations

COMMAND_SET = "SET"
COMMAND_SETP = "SETP"
COMMAND_UNSET = "UNSET"
COMMAND_VER = "VER"
COMMAND_HELP = "HELP"
COMMAND_STATE = "STATE"
COMMAND_FLAGS = "FLAGS"
COMMAND_PRFSTATE = "PRFSTATE"

CONTROL_COMMANDS = frozenset({COMMAND_SET, COMMAND_SETP, COMMAND_UNSET})
QUERY_COMMANDS = frozenset(
    {COMMAND_VER, COMMAND_HELP, COMMAND_STATE, COMMAND_FLAGS, COMMAND_PRFSTATE}
)

SECTION_READY = "READY"
SECTION_ARMED_PART = "ARMED_PART"
SECTION_ARMED = "ARMED"
SECTION_MAINTENANCE = "MAINTENANCE"
SECTION_SERVICE = "SERVICE"
SECTION_BLOCKED = "BLOCKED"
SECTION_OFF = "OFF"

SECTION_STATES = frozenset(
    {
        SECTION_READY,
        SECTION_ARMED_PART,
        SECTION_ARMED,
        SECTION_MAINTENANCE,
        SECTION_SERVICE,
        SECTION_BLOCKED,
        SECTION_OFF,
    }
)

FLAG_INTERNAL_WARNING = "INTERNAL_WARNING"
FLAG_EXTERNAL_WARNING = "EXTERNAL_WARNING"
FLAG_FIRE_ALARM = "FIRE_ALARM"
FLAG_INTRUDER_ALARM = "INTRUDER_ALARM"
FLAG_PANIC_ALARM = "PANIC_ALARM"
FLAG_ENTRY = "ENTRY"
FLAG_EXIT = "EXIT"

FLAGS = frozenset(
    {
        FLAG_INTERNAL_WARNING,
        FLAG_EXTERNAL_WARNING,
        FLAG_FIRE_ALARM,
        FLAG_INTRUDER_ALARM,
        FLAG_PANIC_ALARM,
        FLAG_ENTRY,
        FLAG_EXIT,
    }
)
